package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/marveloper-8/real-time-analytics-dashboard-monorepo/graph/model"
)

// GetAnalytics is the resolver for the getAnalytics field.
func (r *queryResolver) GetAnalytics(ctx context.Context, startTime string, endTime string) (*model.Analytics, error) {
	panic(fmt.Errorf("not implemented: GetAnalytics - getAnalytics"))
}

// AnalyticsUpdated is the resolver for the analyticsUpdated field.
func (r *subscriptionResolver) AnalyticsUpdated(ctx context.Context) (<-chan *model.Analytics, error) {
	panic(fmt.Errorf("not implemented: AnalyticsUpdated - analyticsUpdated"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
