version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=your_influxdb_token
      - INFLUXDB_ORG=your_org
      - INFLUXDB_BUCKET=your_bucket
    depends_on:
      - influxdb
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GRAPHQL_HTTP_URL=http://server:8080/query
      - NEXT_PUBLIC_GRAPHQL_WS_URL=ws://server:8080/query
  
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=your_org
      - DOCKER_INFLUXDB_INIT_BUCKET=your_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your_influxdb_token

volumes:
  influxdb_data: