apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: marveloper/analytics-dashboard-client:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_GRAPHQL_HTTP_URL
          value: "http://server/query"
        - name: NEXT_PUBLIC_GRAPHQL_WS_URL
          value: "ws://server/query"
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 300