apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  org: "your_org"
  bucket: "your_bucket"
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
data:
  admin-password: base64_encoded_password
  admin-token: base64_encoded_token