// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type Analytics struct {
	TotalVisits        int          `json:"totalVisits"`
	UniqueVisitors     int          `json:"uniqueVisitors"`
	AvgSessionDuration float64      `json:"avgSessionDuration"`
	BounceRate         float64      `json:"bounceRate"`
	TopPages           []*PageVisit `json:"topPages"`
}

type PageVisit struct {
	URL    string `json:"url"`
	Visits int    `json:"visits"`
}

type Query struct {
}

type Subscription struct {
}
